# Generated by Django 2.2.4 on 2020-09-13 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0002_images_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='editted_images',
            field=models.ImageField(default=1, upload_to='filters'),
            preserve_default=False,
        ),
    ]
