# Generated by Django 2.2.4 on 2020-09-13 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0004_auto_20200913_1354'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
        migrations.AlterField(
            model_name='images',
            name='editted_images',
            field=models.ImageField(blank=True, null=True, upload_to='filters/'),
        ),
    ]
