# Generated by Django 2.2.4 on 2020-09-13 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0006_auto_20200913_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='is_editted',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
