# Generated by Django 2.2.4 on 2020-09-13 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0007_images_is_editted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='is_editted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
